import type {Metadata} from "next";
import {Public_Sans} from "next/font/google";
import "./globals.css";
import Header from "@/conponents/Header";
import Footer from "@/conponents/Footer";
import NextAuthWrapper from "@/lib/next.auth.wrapper";
import {auth} from "@/auth";

const public_sans = Public_Sans({subsets: ["vietnamese"]});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    return (
        <html lang="en">
        <body
            className={public_sans.className + " min-h-screen flex flex-col"}
        >
        <NextAuthWrapper>

            <Header/>
            <div className="flex-grow">{children}</div>
            <Footer/>
        </NextAuthWrapper>
        </body>
        </html>
    );
}
