import type {Metadata} from "next";
import {Public_Sans} from "next/font/google";
import "./globals.css";
import Header from "@/app/conponents/Header";
import Footer from "@/app/conponents/Footer";

const public_sans = Public_Sans({subsets: ["vietnamese"]});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head></head>
        <body
            className={public_sans.className + " min-h-screen flex flex-col"}
        >
        <Header/>
        <div className="flex-grow">{children}</div>
        <Footer/>
        </body>
        </html>
    );
}
