import type {Metadata} from "next";
import "@/app/globals.css";
import MenuItem from "@/app/admin/MenuItem";
import {Avatar} from "@mui/material";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faGear} from "@fortawesome/free-solid-svg-icons/faGear";
import {faBell} from "@fortawesome/free-solid-svg-icons/faBell";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    const userMenu = {
        title: "User",
        subMenu: [
            "Buyer",
            "Seller",
        ],
    };
    const productMenu = {
        title: "Product",
        subMenu: [
            "All product",
            "Sale",
        ],
    };

    return (
        <>
            <div className="flex w-full">
                <nav className="w-1/6 bg-black text-white p-4 ">
                    <ul>
                        <h3 className="text-white text-left py-3 px-4 hover:bg-gray-800">Genaral</h3>
                        <MenuItem menuData={userMenu}/>
                        <MenuItem menuData={productMenu}/>
                    </ul>
                </nav>
                <div className="w-5/6">
                    <div className="flex bg-gray-100 py-4 p-2 justify-end space-x-4">
                        <FontAwesomeIcon icon={faBell} className="size-8 text-gray-400"/>
                        <FontAwesomeIcon icon={faGear} className="size-8 text-gray-400"/>
                        <Avatar sx={{width: 32, height: 32}}>Ad</Avatar>
                    </div>
                    <div className="bg-gray-100 p-8">
                        {children}
                    </div>
                </div>
            </div>
        </>

    );
}
