import type {Metadata} from "next";
import "@/app/globals.css";
import MenuItem from "@/app/admin/MenuItem";
import {Avatar} from "@mui/material";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faGear} from "@fortawesome/free-solid-svg-icons/faGear";
import {faBell} from "@fortawesome/free-solid-svg-icons/faBell";
import {auth} from "@/auth";
import Link from "next/link";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    const userMenu = {
        title: "User",
        subMenu: [
            "Buyer",
            "Seller",
        ],
    };

    const session = await auth();

    const productMenu = {
        title: "Product",
        subMenu: [
            "All",
            "Sale",
        ],
    };

    return (
        <>
            <div className="flex w-full">
                <nav className="w-1/6 bg-black text-white p-4 ">
                    <ul>
                        <Link href="/admin/dashboard">
                            <div className=" w-full text-white text-left py-3 px-4
                                 hover:bg-gray-800">Dashboard
                            </div>
                        </Link>
                        <MenuItem menuData={userMenu}/>
                        <MenuItem menuData={productMenu}/>
                    </ul>
                </nav>
                <div className="w-5/6">
                    <div className="bg-gray-100 p-8">
                        {children}
                    </div>
                </div>
            </div>
        </>

    );
}
